### ISSUE TITLE
Generate test-kitchen run_list list from generated stencil(s)*

### ISSUE THREAD

**Issue by theborch** [rackerlabs/fastfood#26]
Currently the `.kitchen.yml` file is generated with the default recipe as its run list, but in order to test things on a CI platform or non manual way, we need to generate this run list from the specified stencil(s)* used when building/generating a cookbook.

<sup> * apologies for misusing the terminology -- which I am fairly certain I am doing. </sup>

**Comment by mattjbarlow** [comment]
There are a lot of options that can go into a .kitchen.yml file. For example, even within the suites, there are often times attributes that will need to be overridden. In these cases, a run-list by itself is not very useful.

Maybe there should just be a separate .kitchen.cloud.yml for each cookbook json file. The person who writes a 'Rails' cookbook json file should know which suites to run. What do you think?

**Comment by theborch** [comment]
@mattjbarlow :+1:, however, would love to see the pertinent kitchen config info exist in the cookbook.json  and have .kitchen.yml be generated with that -- thoughts?

For example:
```json
{
  "name": "cookbook",
  "stencils": [
    {
      "stencil_set": "stencil",
      "name": "stencilname",
      "stencil": "stencil_stencil"
    }
  ],
  "test-kitchen": [
    {
      "platforms": [
        {
          "name": "ubuntu-14.04"
        },
        {
          "name": "centos-6.5"
        }
      ]
    },
    {
      "suites": [
        {
          "name": "suite-1",
          "run_list": "stencilname",
          "attributes": {
            "rackspace": {
              "cloud_credentials": {
                "username": "username"
              }
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by jarosser06** [comment]
I'm not sure adding test kitchen specifically as a pass through is a good idea, maybe adding a few keys like platform and building off that would be enough.

**Comment by erulabs** [comment]
Any movement on this? I'd be really nice to have a simple base .kitchen.yml in the "base" stencil, and have newly generated stencils append additional "suites". I can't see a need to have platforms overridden on a per-stencil basis, but I suppose that's nice too. At the very least, I'd love to be able to define additional suites to add to the kitchen.yml file on generation.
