### ISSUE TITLE
Name needs to be defined in addition to stencil set

### ISSUE THREAD

**Issue by erulabs** [rackerlabs/fastfood#28]
Hello,

  Previously (in the Go version), one could:
```json
{
  "name": "my_cookbook",
  "stencils": [ { "stencil_set": "php" } ]
}
```
  The PHP stencil defines a default "name" of "_php", however, this will error out because the stencil_set's name needs to be defined like so:

```json
{
  "name": "my_cookbook",
  "stencils": [ { "name": "_php", "stencil_set": "php" } ]
}
```
  The "name" field should be optional, assuming it's defined as a default in the stencils manifest.

**Comment by jarosser06** [comment]
#29 resolves this issue
