### ISSUE TITLE
Unable to determine the currently installed version

### ISSUE THREAD

**Issue by dexxtreme** [rackerlabs/fastfood#45]
I don't see an easy way to determine the version of fastfood I currently have installed. One (or both) of the following should be added:

1) The version number needs to be displayed in the output when running "fastfood -h"

2) There should be a "--version" command line flag to display the version number

**Comment by jarosser06** [comment]
Resolved with #46

**Comment by samstav** [comment]
@dexxtreme you'll be able to quickly compare your local version to the latest release on PyPI using some updates from this PR as well: https://github.com/rackerlabs/fastfood/pull/47
