### ISSUE TITLE
Need for some method for adding documentation to cookbooks based on recipes utilized

### ISSUE THREAD

**Issue by cybermerc** [rackerlabs/fastfood#61]
Need to be able to add some type of README information to cookbooks based on recipes that are added. Maybe this can be done via a field within the manifest.json ?

**Comment by martinb3** [comment]
I believe #73 solved this, by allowing us to append to an existing file. We could add README.md sections using this technique, similar to [how we're adding .kitchen.yml suites](https://github.com/AutomationSupport/fastfood-templatepack/blob/master/stencils/nginx/manifest.json#L28-L30).
