### ISSUE TITLE
Cannot override templatepack base file in stencil

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/fastfood#67]
I have a stencil that overrides .kitchen.yml from the base template pack. It seems that the base templatepack always writes .kitchen.yml first, and then won't write the rendered template from my stencil over top of it.

This effectively makes it impossible to override a file from the base in a stencil. Combined with #66, there's no way to pass data between the two (template pack and stencil) and no way to override a file's contents from one to the other.

**Comment by jarosser06** [comment]
You can override the file by using the force flag would this suit your needs?

**Comment by martinb3** [comment]
If we use `--force` as a workaround, we lose the feature of 'generate a file if missing but do not overwrite existing file.' We need the ability to override the base, without forcing overwrite of the final file.

Ideally, many, if not all stencils would have overrides, so that their functionality would be runnable and testable on the output cookbook. `--force` would effectively become the default.
